### ISSUE TITLE
Issues with Twilight Forest 

### ISSUE THREAD

**Issue by Vollauro** [BiomeBundle/BiomeBundle#105] opened 2017-11-30 05:21 UTC
Minecraft crashes when loading a chunk that uses the Firefly Forest biome which spawns in the Twilight Forest dimension. OTG produces no issues with Twilight Forest and I haven't experienced any crashes in any of the other biomes with Biome Bundle installed. Only upon loading the Firefly Forest biome does the game crash.

[Crashlog.](https://gist.github.com/Vollauro/6e7b2543b79d312d2b6499565e62dab4)

I don't know if there is a workaround by tweaking configs or the like so I've ended up here searching for some help.

**Comment by Rene211** [comment] 2017-12-02 10:53
Iam having the same Problem.
Pretty sad. I like both mods :/

**Comment by luthienanarion** [comment] 2017-12-03 21:19
This is caused by an issue in OTG.

https://github.com/PG85/OpenTerrainGenerator/issues/76

**Comment by Wisecompany** [comment] 2018-01-16 17:13
@luthienanarion Are you sure? I thought The Twilight Forest resolved it with a workaround here: [https://github.com/TeamTwilight/twilightforest/commit/1d829d06fd3f67a6326b891ca3f1e80b79f4e5a0](https://github.com/TeamTwilight/twilightforest/commit/1d829d06fd3f67a6326b891ca3f1e80b79f4e5a0)

I too cannot enter the TF because of this bug.

**Comment by ShinyTurtles** [comment] 2018-09-23 09:32
Any workaround for this problem discovered so far?

**Comment by BiomeBundle** [comment] 2020-08-29 11:45
Fixed on OTG's end

**Closed** 2020-08-29 11:44 UTC
