### ISSUE TITLE
ID Conflict in DireWolf20 Mod Pack.

### ISSUE THREAD

**Issue by AngelicBeatz** [BiomeBundle/BiomeBundle#15] opened 2017-01-05 17:01 UTC
This is the latest error, a 1.3.1 direwolf pack Pit. This is a brand new install but meh, I am going to try what others are doing and get a full pregen going unless you guys are already on the verge of releasing a pregened world.

http://pastebin.com/VV3diP34

**Comment by MCPitman** [comment] 2017-01-05 18:45
Going to close this as it is not a bug, either disable BoP (which is incompatible as mentioned in the website FAQ) or edit your configs to not create an ID mismatch.

I'm not sure what you mean by a full pregen but if you are planning to play a pregenerated world in a modpack - unless you generate the world with the modpack installed, no ores/stones or other blocks from your mods will be available in your pregenerated world.

**Closed by MCPitman** 2017-01-05 18:45 UTC
