### ISSUE TITLE
Locate Command completely break

### ISSUE THREAD

**Issue by SkillzGamingYT** [BiomeBundle/BiomeBundle#124] opened 2018-01-15 12:27 UTC
/locate "something" will give out false XYZ. Village, Temple, etc...

**Comment by MCPitman** [comment] 2018-01-20 17:55
/locate works in single player/forge.

Are you using Spigot? Is the BBundle world generated via multiverse?

**Comment by SkillzGamingYT** [comment] 2018-01-21 05:54
No, i'm not using spigot. I'm using Forge.

What forge version are you using?

**Comment by MCPitman** [comment] 2018-07-29 17:45
This has not been reported by anyone else and I cannot reproduce it so I'm closing this for now.

**Closed by MCPitman** 2018-07-29 17:45 UTC
